variables and functions
ChrisNewmanGDL/PFMCPP_Project2 pull request #1
Opened 2021-06-15 07:50 UTC by ChrisNewmanGDL

Hi, the code ran ok, but I didn't understand the warnings I got -  "implicit conversion loses floating point precision"
I get that double has more precision than float, but dont know when is it best to use double or float?

2021-06-16 00:12 UTC, matkatmusic requested changes
You have lots of code formatting issues.
Always strive to make your code as easy to read as possible by making sure it is consistently formatted and indented.
I have marked specific spots that need attention.
- [ ] revise

2021-06-16 00:12 UTC, matkatmusic commented on main.cpp
> +}
Fix this indentation
- [ ] revise

2021-06-16 00:12 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(inputNoteFrequency, third, fifth);
you are initializing your `float` function arguments with doubles.
- [ ] revise

2021-06-16 00:12 UTC, matkatmusic commented on main.cpp
> +    bool markThis = validSubmission(2000,1.5, 1);
Be consistent with your spacing around your function parameters.
- [ ] revise

2021-06-16 00:12 UTC, matkatmusic commented on main.cpp
> +    ignoreUnused(carRented,pitchArea,phraseLength,grandaughterTantrumLikelihood, playNote, blowWhistle, markThis, enterPlayground, podcastLength, addChordTones, meetingQuorate);
Be consistent with your spacing around your function parameters
Consult the coding style example in the Readme.MD if you aren't sure what is wrong with these lines of code with regard to the coding style.
- [ ] revise

2021-06-16 00:12 UTC, matkatmusic commented on main.cpp
> +    grandaughterTantrumLikelihood (3, 1);
Be consistent with your spacing around your function parameters
Consult the coding style example in the Readme.MD if you aren't sure what is wrong with these lines of code with regard to the coding style.
- [ ] revise

2021-06-16 00:12 UTC, matkatmusic commented on main.cpp
> +double minisculeThingSize = 0.0000000000234;
Fix this indentation
- [ ] revise

2021-06-18 05:18 UTC, matkatmusic requested changes

2021-06-18 05:18 UTC, matkatmusic commented on main.cpp
> +double minisculeThingSize = 0.0000000000234;
All of these variables need to be indented correctly.
Line them up with `int number = 2;`
Please take a look at the Readme.MD.  There is a coding standard example that demonstrates the coding standard for the course. 
- [ ] revise

2021-06-18 08:36 UTC, ChrisNewmanGDL commented on main.cpp
> +double minisculeThingSize = 0.0000000000234;
ok - I had an eye test the other day too!

2021-06-18 09:21 UTC, matkatmusic approved these changes

2021-06-18 09:21 UTC, merged